import { useCallback, useEffect, useRef, useState } from "react";

export type CallKind = "voice" | "video";
export type CallStatus = "idle" | "requesting-permission" | "connecting" | "connected" | "permission-denied" | "failed";
export type PeerSignal = { type: "offer" | "answer" | "ice-candidate"; payload: RTCSessionDescriptionInit | RTCIceCandidateInit };
export type TransferState = { id: string; name: string; sent: number; total: number; status: "sending" | "receiving" | "resumed" | "complete" | "cancelled" | "rejected"; direction: "send" | "receive" } | null;
export type ReceivedFile = { name: string; mime: string; size: number; url: string } | null;
export const MAX_PEER_FILE_BYTES = 25 * 1024 * 1024;

export function useWebRtcCall(onSignal?: (signal: PeerSignal) => void, onText?: (body: string) => void) {
  const peerRef = useRef<RTCPeerConnection | null>(null); const streamRef = useRef<MediaStream | null>(null); const channelRef = useRef<RTCDataChannel | null>(null);
  const metaRef = useRef<{ id: string; name: string; mime: string; size: number } | null>(null); const chunksRef = useRef<ArrayBuffer[]>([]); const receivedBytesRef = useRef(0); const cancelRef = useRef(false); const currentFileRef = useRef<File | null>(null); const transferIdRef = useRef(""); const readyResolverRef = useRef<((offset: number) => void) | null>(null);
  const [status, setStatus] = useState<CallStatus>("idle"); const [kind, setKind] = useState<CallKind | null>(null); const [stream, setStream] = useState<MediaStream | null>(null); const [remoteStream, setRemoteStream] = useState<MediaStream | null>(null); const [muted, setMuted] = useState(false); const [cameraOff, setCameraOff] = useState(false); const [screenSharing, setScreenSharing] = useState(false); const [screenShareStatus, setScreenShareStatus] = useState<"idle" | "requesting" | "active" | "denied" | "failed">("idle"); const [transfer, setTransfer] = useState<TransferState>(null); const [receivedFile, setReceivedFile] = useState<ReceivedFile>(null); const screenTrackRef = useRef<MediaStreamTrack | null>(null);

  const attachChannel = useCallback((channel: RTCDataChannel) => { channel.binaryType = "arraybuffer"; channel.onmessage = (event) => { if (typeof event.data === "string") { try { const packet = JSON.parse(event.data) as { type: string; id?: string; name?: string; mime?: string; size?: number; offset?: number; body?: string }; if (packet.type === "chat-text" && typeof packet.body === "string") onText?.(packet.body); if (packet.type === "file-ready" && packet.id === transferIdRef.current) { readyResolverRef.current?.(Math.max(0, packet.offset ?? 0)); readyResolverRef.current = null; } if (packet.type === "file-meta" && packet.id && packet.name && packet.mime && typeof packet.size === "number") { if (packet.size > MAX_PEER_FILE_BYTES) { channel.send(JSON.stringify({ type: "file-cancel", id: packet.id })); return; } metaRef.current = { id: packet.id, name: packet.name, mime: packet.mime, size: packet.size }; chunksRef.current = []; receivedBytesRef.current = Math.min(packet.offset ?? 0, packet.size); setTransfer({ id: packet.id, name: packet.name, sent: receivedBytesRef.current, total: packet.size, status: receivedBytesRef.current > 0 ? "resumed" : "receiving", direction: "receive" }); channel.send(JSON.stringify({ type: "file-ready", id: packet.id, offset: receivedBytesRef.current })); } if (packet.type === "file-cancel" && packet.id === metaRef.current?.id) { metaRef.current = null; chunksRef.current = []; receivedBytesRef.current = 0; setTransfer((current) => current ? { ...current, status: "cancelled" } : current); } if (packet.type === "file-end" && metaRef.current && packet.id === metaRef.current.id && receivedBytesRef.current === metaRef.current.size) { const blob = new Blob(chunksRef.current, { type: metaRef.current.mime }); setReceivedFile({ ...metaRef.current, url: URL.createObjectURL(blob) }); setTransfer({ id: metaRef.current.id, name: metaRef.current.name, sent: metaRef.current.size, total: metaRef.current.size, status: "complete", direction: "receive" }); metaRef.current = null; chunksRef.current = []; receivedBytesRef.current = 0; } } catch { /* Ignore malformed peer packets. */ } return; } const chunk = event.data instanceof ArrayBuffer ? event.data : null; if (chunk && metaRef.current && receivedBytesRef.current + chunk.byteLength <= metaRef.current.size) { chunksRef.current.push(chunk); receivedBytesRef.current += chunk.byteLength; setTransfer((current) => current ? { ...current, sent: receivedBytesRef.current, status: current.status === "resumed" ? "resumed" : "receiving" } : current); } }; }, []);

  const createPeer = useCallback((localStream: MediaStream, callKind: CallKind) => { const peer = new RTCPeerConnection({ iceServers: [{ urls: "stun:stun.l.google.com:19302" }] }); localStream.getTracks().forEach((track) => peer.addTrack(track, localStream)); peer.ontrack = (event) => setRemoteStream(event.streams[0] ?? null); peer.onicecandidate = (event) => { if (event.candidate) onSignal?.({ type: "ice-candidate", payload: event.candidate.toJSON() }); }; peer.onconnectionstatechange = () => { if (peer.connectionState === "connected") setStatus("connected"); if (["failed", "closed"].includes(peer.connectionState)) setStatus("failed"); }; peer.ondatachannel = (event) => { channelRef.current = event.channel; attachChannel(event.channel); }; channelRef.current = peer.createDataChannel("veilchat-file-transfer"); attachChannel(channelRef.current); peerRef.current = peer; streamRef.current = localStream; setStream(localStream); setKind(callKind); return peer; }, [attachChannel, onSignal]);
  const endCall = useCallback(() => { peerRef.current?.close(); peerRef.current = null; channelRef.current = null; streamRef.current?.getTracks().forEach((track) => track.stop()); screenTrackRef.current?.stop(); streamRef.current = null; setStream(null); setRemoteStream(null); setKind(null); setStatus("idle"); setMuted(false); setCameraOff(false); setScreenSharing(false); setScreenShareStatus("idle"); setTransfer(null); }, []);
  const startCall = useCallback(async (callKind: CallKind) => { endCall(); setStatus("requesting-permission"); try { const localStream = await navigator.mediaDevices.getUserMedia({ audio: true, video: callKind === "video" }); const peer = createPeer(localStream, callKind); const offer = await peer.createOffer(); await peer.setLocalDescription(offer); onSignal?.({ type: "offer", payload: offer }); setStatus("connecting"); } catch (error) { setStatus(error instanceof DOMException && ["NotAllowedError", "PermissionDeniedError"].includes(error.name) ? "permission-denied" : "failed"); setKind(null); } }, [createPeer, endCall, onSignal]);
  const applySignal = useCallback(async (signal: PeerSignal) => { if (signal.type === "offer" && !peerRef.current) { try { setStatus("requesting-permission"); const localStream = await navigator.mediaDevices.getUserMedia({ audio: true, video: kind === "video" }); const peer = createPeer(localStream, kind ?? "video"); await peer.setRemoteDescription(signal.payload as RTCSessionDescriptionInit); const answer = await peer.createAnswer(); await peer.setLocalDescription(answer); onSignal?.({ type: "answer", payload: answer }); setStatus("connecting"); } catch { setStatus("failed"); } return; } const peer = peerRef.current; if (!peer) return; if (signal.type === "answer") await peer.setRemoteDescription(signal.payload as RTCSessionDescriptionInit); if (signal.type === "ice-candidate") await peer.addIceCandidate(signal.payload as RTCIceCandidateInit); }, [createPeer, kind, onSignal]);
  const sendText = useCallback((body: string) => { const channel = channelRef.current; if (!channel || channel.readyState !== "open") return false; channel.send(JSON.stringify({ type: "chat-text", body: body.slice(0, 10000) })); return true; }, []); const sendFile = useCallback(async (file: File, startOffset = 0) => { const channel = channelRef.current; if (!channel || channel.readyState !== "open" || file.size > MAX_PEER_FILE_BYTES) { setTransfer({ id: transferIdRef.current || crypto.randomUUID(), name: file.name, sent: 0, total: file.size, status: "rejected", direction: "send" }); return false; } const id = transferIdRef.current || crypto.randomUUID(); transferIdRef.current = id; currentFileRef.current = file; cancelRef.current = false; setTransfer({ id, name: file.name, sent: startOffset, total: file.size, status: startOffset > 0 ? "resumed" : "sending", direction: "send" }); channel.send(JSON.stringify({ type: "file-meta", id, name: file.name, mime: file.type, size: file.size, offset: startOffset })); const confirmedOffset = await new Promise<number>((resolve) => { readyResolverRef.current = resolve; window.setTimeout(() => { if (readyResolverRef.current) { readyResolverRef.current = null; resolve(startOffset); } }, 500); }); const offsetStart = Math.min(file.size, Math.max(startOffset, confirmedOffset)); const buffer = await file.arrayBuffer(); const chunkSize = 16 * 1024; for (let offset = offsetStart; offset < buffer.byteLength; offset += chunkSize) { if (cancelRef.current) { setTransfer((current) => current ? { ...current, sent: offset, status: "cancelled" } : current); channel.send(JSON.stringify({ type: "file-cancel", id })); return false; } while (channel.bufferedAmount > 2 * 1024 * 1024) await new Promise((resolve) => window.setTimeout(resolve, 30)); const chunk = buffer.slice(offset, Math.min(offset + chunkSize, buffer.byteLength)); channel.send(chunk); setTransfer({ id, name: file.name, sent: Math.min(offset + chunkSize, file.size), total: file.size, status: offsetStart > 0 ? "resumed" : "sending", direction: "send" }); } channel.send(JSON.stringify({ type: "file-end", id })); setTransfer({ id, name: file.name, sent: file.size, total: file.size, status: "complete", direction: "send" }); transferIdRef.current = ""; return true; }, []);
  const cancelTransfer = useCallback(() => { cancelRef.current = true; setTransfer((current) => current ? { ...current, status: "cancelled" } : current); }, []); const resumeTransfer = useCallback(() => { if (currentFileRef.current && transfer && transfer.status === "cancelled") void sendFile(currentFileRef.current, transfer.sent); }, [sendFile, transfer]); const saveReceivedFile = useCallback(() => { if (!receivedFile) return; const anchor = document.createElement("a"); anchor.href = receivedFile.url; anchor.download = receivedFile.name; anchor.click(); }, [receivedFile]);
  const shareScreen = useCallback(async () => { const peer = peerRef.current; if (!peer) return; setScreenShareStatus("requesting"); try { const display = await navigator.mediaDevices.getDisplayMedia({ video: true, audio: false }); const track = display.getVideoTracks()[0]; const sender = peer.getSenders().find((item) => item.track?.kind === "video"); if (!sender || !track) { display.getTracks().forEach((item) => item.stop()); setScreenShareStatus("failed"); return; } await sender.replaceTrack(track); screenTrackRef.current = track; setScreenSharing(true); setScreenShareStatus("active"); track.onended = () => { setScreenSharing(false); setScreenShareStatus("idle"); }; } catch (error) { setScreenShareStatus(error instanceof DOMException && ["NotAllowedError", "PermissionDeniedError"].includes(error.name) ? "denied" : "failed"); } }, []);
  const stopScreenShare = useCallback(async () => { const peer = peerRef.current; const track = screenTrackRef.current; if (!peer || !track) return; track.stop(); const cameraTrack = streamRef.current?.getVideoTracks()[0]; const sender = peer.getSenders().find((item) => item.track?.kind === "video"); if (sender && cameraTrack) await sender.replaceTrack(cameraTrack); screenTrackRef.current = null; setScreenSharing(false); setScreenShareStatus("idle"); }, []);
  const toggleMute = useCallback(() => { const next = !muted; streamRef.current?.getAudioTracks().forEach((track) => { track.enabled = !next; }); setMuted(next); }, [muted]); const toggleCamera = useCallback(() => { const next = !cameraOff; streamRef.current?.getVideoTracks().forEach((track) => { track.enabled = !next; }); setCameraOff(next); }, [cameraOff]); useEffect(() => endCall, [endCall]);
  return { status, kind, stream, remoteStream, muted, cameraOff, screenSharing, screenShareStatus, transfer, receivedFile, startCall, endCall, applySignal, sendText, sendFile, cancelTransfer, resumeTransfer, saveReceivedFile, shareScreen, stopScreenShare, toggleMute, toggleCamera };
}
