import { useEffect, useRef, useState } from "react";
import QRCode from "qrcode";
import { Html5Qrcode } from "html5-qrcode";
import { Button } from "@/components/ui/button";
import { CheckCircle2, QrCode, ScanLine } from "lucide-react";
import { isPeerSignalEnvelope, type PeerSignalEnvelope } from "@shared/webrtc";

export function SignalQr({ value, onScanned }: { value: string; onScanned: (value: PeerSignalEnvelope) => void }) {
  const [qrUrl, setQrUrl] = useState<string | null>(null); const [scanning, setScanning] = useState(false); const [success, setSuccess] = useState(false); const [scannedIdentity, setScannedIdentity] = useState<PeerSignalEnvelope["identity"]>(undefined); const [error, setError] = useState<string | null>(null); const scannerRef = useRef<Html5Qrcode | null>(null);
  useEffect(() => { if (!value) { setQrUrl(null); return; } QRCode.toDataURL(value, { width: 180, margin: 2, color: { dark: "#071014", light: "#8ff5ff" } }).then(setQrUrl).catch(() => setError("Unable to create signaling QR.")); }, [value]);
  const stop = async () => { if (scannerRef.current) { await scannerRef.current.stop().catch(() => undefined); scannerRef.current.clear(); scannerRef.current = null; } setScanning(false); };
  const start = async () => { setError(null); setSuccess(false); setScanning(true); const scanner = new Html5Qrcode("veilchat-signal-reader"); scannerRef.current = scanner; try { await scanner.start({ facingMode: "environment" }, { fps: 10, qrbox: 190 }, (raw) => { try { const parsed = JSON.parse(raw) as unknown; if (!isPeerSignalEnvelope(parsed)) throw new Error("invalid"); setSuccess(true); setScannedIdentity(parsed.identity); onScanned(parsed); void stop(); } catch { setError("That QR code is not a valid VeilChat signal."); } }, () => undefined); } catch { setError("Camera unavailable. Use copy/paste signaling instead."); setScanning(false); } };
  return <div className="space-y-2"><div className="flex flex-wrap items-center gap-3"><div className="grid size-[180px] place-items-center rounded-xl bg-cyan-100 p-2">{qrUrl ? <img src={qrUrl} alt="WebRTC signaling QR" className="size-full rounded-lg" /> : <QrCode className="size-8 text-slate-500" />}</div><div className="min-w-0 flex-1"><div className="font-mono text-[10px] uppercase tracking-wider text-cyan-200">Peer signal QR</div><p className="mt-1 text-[10px] leading-4 text-slate-500">Short-lived offer, answer, or ICE data only. Never includes passwords or private keys.</p><div className="mt-2 flex gap-2"><Button type="button" variant="outline" onClick={() => void start()} disabled={scanning || !value} className="border-white/10 bg-transparent text-[10px] text-slate-300">Scan signal</Button>{scanning && <Button type="button" variant="outline" onClick={() => void stop()} className="border-white/10 bg-transparent text-[10px] text-slate-300">Stop</Button>}</div></div></div>{scanning && <div className="relative max-w-sm overflow-hidden rounded-xl border border-cyan-300/30 bg-black"><div id="veilchat-signal-reader" className="min-h-[240px]" /><div className="pointer-events-none absolute inset-0 grid place-items-center"><div className="relative size-48 border border-cyan-300/70 shadow-[0_0_0_999px_rgba(3,8,12,0.52)]"><span className="absolute -left-px -top-px size-7 border-l-2 border-t-2 border-cyan-200" /><span className="absolute -right-px -top-px size-7 border-r-2 border-t-2 border-cyan-200" /><span className="absolute -bottom-px -left-px size-7 border-b-2 border-l-2 border-cyan-200" /><span className="absolute -bottom-px -right-px size-7 border-b-2 border-r-2 border-cyan-200" /><span className="absolute left-0 right-0 top-1/2 h-px animate-pulse bg-cyan-300" /></div></div><div className="absolute bottom-2 left-1/2 flex -translate-x-1/2 items-center gap-1 rounded-full bg-black/70 px-2 py-1 font-mono text-[9px] text-cyan-100"><ScanLine className="size-3" /> align code</div></div>}{success && <div className="rounded-lg border border-emerald-300/20 bg-emerald-300/[0.05] px-3 py-2 font-mono text-[10px] text-emerald-200"><div className="flex items-center gap-2"><CheckCircle2 className="size-4" /> Signal scanned. Confirm the peer before connecting.</div>{scannedIdentity && <div className="mt-2 space-y-1 pl-6 text-[9px] text-emerald-100/70"><div>peer: {scannedIdentity.username}</div><div>key fingerprint: {scannedIdentity.publicKeyFingerprint}</div></div>}</div>}{error && <div className="font-mono text-[10px] text-rose-300">{error}</div>}</div>;
}
